name: Create Client Installer

on:
  workflow_dispatch: # A la main pour l'instant

jobs:
  run-batch:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # - name: Setup Gradle 8.5
      #   uses: gradle/actions/setup-gradle@v4
      #   with:
      #     gradle-version: "8.5"

      - name: Run Gradle createClientInstaller
        run: .\gradlew :projects:client:createClientInstaller

      - name: Prepare upload
        run: |
          cd dist\Client
          $exe = Get-ChildItem -Path . -Filter "*.exe" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          echo "EXE_NAME=dist/Client/$($exe.Name)" >> $env:GITHUB_ENV

      - name: Upload .exe as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-executable
          path: ${{ env.EXE_NAME }}